### ISSUE TITLE
Elastic minimum version requirement

### ISSUE THREAD

**Issue by rpalcolea** [elastic/idea-indexing-metrics-collector#9]
Hi @breskeby 

Wonder what are your thoughts on the following

I see you have

```
elasticsearch-java:8.1.2
``` 

And also noticed the following when trying with an old version of elastic:

```
[es/indices.exists] Missing [X-Elastic-Product] header. Please check that you are connecting to an Elasticsearch instance, and that any networking filters are preserving that header.
``` 

Looks like this was introduced back in 8.x https://github.com/elastic/elasticsearch/commit/c06608d4e67fbbe132675c84bb581400e0f77694 and I guess related to https://github.com/elastic/elasticsearch/issues/73424

Wondering if either:

1. The java client could be downgraded to support older versions of elastic (I wish we all could run with latest and greatest 😭 ) OR
2. Call out in the README that ElasticSearch 8 might be the minimum supported version?

Thoughts?

**Comment by breskeby** [comment]
I could definitely update the docs. But supporting elastic 7.x is quite some effort I think

**Comment by rpalcolea** [comment]
I'll close this then :) thanks!

**Comment by breskeby** [comment]
@rpalcolea Actually I took a look and I could try using an older elasticsearch java client version as this client is meant to be forward compatible. which elasticsearch version do you use?

**Comment by rpalcolea** [comment]
oh that would be nice. We use 5, 6 and possibly 7 if necessary

**Comment by breskeby** [comment]
I've changed the java client to be 7.17.3. That should provide 7.x support. 5 and 6 is just to much hassle given those elasticsearch versions are quite outdated

**Comment by rpalcolea** [comment]
nice! I'll keep an eye for the next release then! thanks again!

**Comment by breskeby** [comment]
@rpalcolea Can you give 0.9.2 a try?
